#!/bin/bash
#
# glassfish4    GlassFish Server Open Source Edition 4.0
#
# chkconfig: 345 70 30
# description: GlassFish Server is a Java EE Application Server Platform
# processname: glassfish4

# Source function library.
. /etc/init.d/functions

RETVAL=0
prog="hiveserver2"
LOCKFILE=/var/lock/subsys/$prog

# Declare variables for GlassFish Server
source /etc/profile

start() {
        echo -n "Starting $prog: "
        $prog --hiveconf hive.root.logger=INFO,console >> /var/log/hiveserver2 2>&1 &
}

stop() {
        echo -n "Shutting down $prog: "
        hive2_pid=`pgrep -f org.apache.hive.service.server.HiveServer2`

        if [[ -n "$hive2_pid" ]]
        then
            echo "Found hivesevrer2 PID-- "$hive2_pid
            kill $hive2_pid
            # if process is still around, use kill -9
            if ps -p $hive2_pid > /dev/null ; then
                echo "Initial kill failed, killing with -9 "
                kill -9 $hive2_pid
            fi
        echo "Hive server2 stopped successfully"
        else
            echo "Hiveserver2 process not found , Hiveserver2 is not running !!!"
        fi
}

status() {
        hive2_pid=`pgrep -f org.apache.hive.service.server.HiveServer2`

        if [[ -n "$hive2_pid" ]]
        then
            echo "Hiveserver2 is running"
        else
            echo "Hiverserver2 is stopped"
        fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
exit 0